[tool.poetry]
name = "blur_app"
version = "0.1.0"
description = "A project for face and number plate blurring using YOLOX and ByteTrack."
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
yolox = "*"
bytetrack = "*"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
notebook = "^6.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
